In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [3]:
dataset = pd.read_csv('plant_health_data.csv')
dataset.head()

Timestamp  Plant_ID  Soil_Moisture  Ambient_Temperature  \
0  2024-10-03 10:54:53.407995         1      27.521109            22.240245   
1  2024-10-03 16:54:53.407995         1      14.835566            21.706763   
2  2024-10-03 22:54:53.407995         1      17.086362            21.180946   
3  2024-10-04 04:54:53.407995         1      15.336156            22.593302   
4  2024-10-04 10:54:53.407995         1      39.822216            28.929001   

   Soil_Temperature   Humidity  Light_Intensity   Soil_pH  Nitrogen_Level  \
0         21.900435  55.291904       556.172805  5.581955       10.003650   
1         18.680892  63.949181       596.136721  7.135705       30.712562   
2         15.392939  67.837956       591.124627  5.656852       29.337002   
3         22.778394  58.190811       241.412476  5.584523       16.966621   
4         18.100937  63.772036       444.493830  5.919707       10.944961   

   Phosphorus_Level  Potassium_Level  Chlorophyll_Content  \
0         45.806852        39.076199            35.703006   
1         25.394393        17.944826            27.993296   
2         27.573892        35.706530            43.646308   
3         26.180705        26.257746            37.838095   
4         37.898907        37.654483            48.265812   

   Electrochemical_Signal Plant_Health_Status  
0                0.941402         High Stress  
1                0.164899         High Stress  
2                1.081728         High Stress  
3                1.186088         High Stress  
4                1.609805         High Stress

In [4]:
dataset.describe()

Plant_ID  Soil_Moisture  Ambient_Temperature  Soil_Temperature  \
count  1200.000000    1200.000000          1200.000000       1200.000000   
mean      5.500000      25.106918            23.999130         19.957794   
std       2.873479       8.677725             3.441561          2.932073   
min       1.000000      10.000724            18.001993         15.003710   
25%       3.000000      17.131893            21.101766         17.353027   
50%       5.500000      25.168333            23.889044         19.911473   
75%       8.000000      32.370231            27.042634         22.596851   
max      10.000000      39.993164            29.990886         24.995929   

          Humidity  Light_Intensity      Soil_pH  Nitrogen_Level  \
count  1200.000000      1200.000000  1200.000000     1200.000000   
mean     54.853165       612.637265     6.524102       30.106751   
std       8.784916       228.318853     0.581755       11.514396   
min      40.028758       200.615482     5.507392       10.003650   
25%      47.019694       416.878983     6.026042       20.249774   
50%      54.692069       617.240221     6.540524       30.138590   
75%      62.451053       811.474690     7.030039       40.184737   
max      69.968871       999.856262     7.497823       49.951136   

       Phosphorus_Level  Potassium_Level  Chlorophyll_Content  \
count       1200.000000      1200.000000          1200.000000   
mean          30.264484        30.112088            34.749591   
std           11.466846        11.668085             8.766995   
min           10.017690        10.000606            20.025511   
25%           20.894445        19.585561            27.463350   
50%           30.019385        30.495054            34.433427   
75%           40.131459        40.108296            42.232637   
max           49.980700        49.981945            49.990811   

       Electrochemical_Signal  
count             1200.000000  
mean                 0.987764  
std                  0.575116  
min                  0.002376  
25%                  0.487982  
50%                  0.981647  
75%                  1.473142  
max                  1.996116

In [213]:
features = dataset.drop(columns= ['Timestamp', 'Plant_ID', 'Plant_Health_Status'], axis= 1)
target = dataset['Plant_Health_Status']

In [214]:
dataset['Plant_Health_Status'].value_counts()

Plant_Health_Status
High Stress        500
Moderate Stress    401
Healthy            299
Name: count, dtype: int64

In [215]:
dataset.isnull().sum()

Timestamp                 0
Plant_ID                  0
Soil_Moisture             0
Ambient_Temperature       0
Soil_Temperature          0
Humidity                  0
Light_Intensity           0
Soil_pH                   0
Nitrogen_Level            0
Phosphorus_Level          0
Potassium_Level           0
Chlorophyll_Content       0
Electrochemical_Signal    0
Plant_Health_Status       0
dtype: int64

In [216]:
# from sklearn.preprocessing import StandardScaler
# scaling = StandardScaler()
# features = scaling.fit_transform(features)

In [217]:
target

0           High Stress
1           High Stress
2           High Stress
3           High Stress
4           High Stress
             ...       
1195    Moderate Stress
1196        High Stress
1197    Moderate Stress
1198            Healthy
1199    Moderate Stress
Name: Plant_Health_Status, Length: 1200, dtype: object

In [218]:
from sklearn.model_selection import train_test_split

Xtrain, Xtest, ytrain, ytest = train_test_split(features, target, test_size= 0.4, random_state= 42)

In [219]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_train_resampled, y_train_resampled = smote.fit_resample(Xtrain, ytrain)

In [220]:
y_train_resampled.value_counts()

Plant_Health_Status
Moderate Stress    297
Healthy            297
High Stress        297
Name: count, dtype: int64

In [221]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators= 100, criterion= 'entropy', max_depth= 3, random_state=42)
model.fit(X_train_resampled, y_train_resampled)

RandomForestClassifier(criterion='entropy', max_depth=3, random_state=42)

In [222]:
train_predict = model.predict(X_train_resampled)
test_predict = model.predict(Xtest)


In [223]:
from sklearn.metrics import accuracy_score
print(f'Training accuracu : {accuracy_score(train_predict, y_train_resampled)}')
print(f'Testing accuracy : {accuracy_score(ytest, test_predict)}')

Training accuracu : 0.9977553310886644
Testing accuracy : 0.9979166666666667


In [224]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_train_resampled, train_predict))

[[297   0   0]
 [  0 297   0]
 [  2   0 295]]


In [225]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(ytest, test_predict))

[[112   0   0]
 [  0 203   0]
 [  0   1 164]]


In [226]:
from sklearn.metrics import accuracy_score, precision_score, f1_score, recall_score
print('Accuracy Score',accuracy_score(ytest, test_predict)*100,'%')
print('Precision Macro Score',precision_score(ytest, test_predict,average = 'macro')*100,'%')
print('Recall_Score',recall_score(ytest, test_predict, average = 'macro')*100,'%')
print('F_Score',f1_score(ytest, test_predict, average = 'macro')*100,'%')

Accuracy Score 99.79166666666667 %
Precision Macro Score 99.83660130718954 %
Recall_Score 99.7979797979798 %
F_Score 99.8167827955062 %


In [228]:
from joblib import dump
dump(model, 'plant_health_model.joblib')

['plant_health_model.joblib']